const projects = [
  {
    id: 'workflow-automation-platform',
    title: 'AI Workflow Automation Platform',
    tagline: 'A Zapier/n8n-style visual workflow builder with real AI integrations',
    image: '/projects/workflow-automation-placeholder.jpg',
    github: 'https://github.com/Mayankkvv',
    demo: '',
    techStack: ['MongoDB Atlas', 'Express', 'React', 'Node.js', 'Redis', 'BullMQ', 'Socket.IO', 'React Flow', 'Zustand', 'Groq API'],
    features: [
      'Visual drag-and-drop workflow builder using React Flow',
      'Background job processing with Redis + BullMQ',
      'Real-time execution updates via Socket.IO',
      'OAuth integrations: GitHub, Discord, Gmail, Google Drive, Slack',
    ],
    metrics: [
      { label: 'OAuth Integrations', value: '5' },
      { label: 'Build Steps', value: '31' },
    ],
    architectureImage: '/projects/workflow-automation-architecture-placeholder.jpg',
  },
  {
    id: 'packet-analyzer',
    title: 'DPI Engine (Packet Analyzer)',
    tagline: 'Multi-threaded C++ Deep Packet Inspection engine for real-world traffic classification',
    image: '/projects/packet-analyzer-placeholder.jpg',
    github: 'https://github.com/Mayankkvv/Packet_analyzer',
    demo: '',
    techStack: ['C++17', 'CMake', 'PCAP', 'Python'],
    features: [
      'Classifies traffic into 20+ real-world apps (YouTube, Netflix, WhatsApp, etc.) without decrypting HTTPS',
      'Flow-based blocking for efficient traffic matching',
      'Multi-threaded pipeline: Reader → Load Balancer → Fast Path workers',
    ],
    metrics: [
      { label: 'Apps Classified', value: '20+' },
      { label: 'Language', value: 'C++17' },
    ],
    architectureImage: '/projects/packet-analyzer-architecture-placeholder.jpg',
  },
  {
    id: 'research-agent',
    title: 'Autonomous AI Research Agent',
    tagline: 'A three-agent Planner–Researcher–Critic pipeline for autonomous research tasks',
    image: '/projects/research-agent-placeholder.jpg',
    github: 'https://github.com/Mayankkvv',
    demo: '',
    techStack: ['Python', 'FastAPI', 'Groq', 'LLaMA 3'],
    features: [
      'Three-agent Planner-Researcher-Critic pipeline',
      'Deployed on Render',
      'Extended and benchmarked on the GAIA benchmark (Hugging Face Agents Course)',
    ],
    metrics: [
      { label: 'GAIA Level 1', value: '20%' },
      { label: 'Agent Roles', value: '3' },
    ],
    architectureImage: '/projects/research-agent-architecture-placeholder.jpg',
  },
  {
    id: 'dynamic-pricing-engine',
    title: 'Dynamic Pricing Engine',
    tagline: 'PLACEHOLDER — add your real description here',
    image: '/projects/dynamic-pricing-placeholder.jpg',
    github: '',
    demo: '',
    techStack: ['PLACEHOLDER'],
    features: ['PLACEHOLDER — add real features'],
    metrics: [{ label: 'PLACEHOLDER', value: '—' }],
    architectureImage: '/projects/dynamic-pricing-architecture-placeholder.jpg',
  },
  {
    id: 'netflix-retention-intelligence',
    title: 'Netflix Retention Intelligence',
    tagline: 'PLACEHOLDER — add your real description here',
    image: '/projects/netflix-retention-placeholder.jpg',
    github: '',
    demo: '',
    techStack: ['PLACEHOLDER'],
    features: ['PLACEHOLDER — add real features'],
    metrics: [{ label: 'PLACEHOLDER', value: '—' }],
    architectureImage: '/projects/netflix-retention-architecture-placeholder.jpg',
  },
]

export default projects